### ISSUE TITLE
"Required privilege is not held by the client" error during dotnetsdk build

### ISSUE THREAD

**Issue by krtarwood** [Sitecore/Helix.Examples#108]
I've followed the quickstart guide and receive the below error message during the dotnetsdk build step of the NETCORE_BUILD_IMAGE build. This occurs during the docker-compose up -d command in the helix-basic-aspnetcore directory. I performed a successful init on this folder prior. So far this occurs on both machines I've tested it on.

<pre>Step 6/10 : RUN Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v$env:NUGET_VERSION/nuget.exe" -UseBasicParsing -OutFile "$env:ProgramFiles\NuGet\nuget.exe"

 ---> Running in b1f140b8605b
Invoke-WebRequest : A required privilege is not held by the client.
At line:1 char:76
+ ... yContinue'; Invoke-WebRequest https://dist.nuget.org/win-x86-commandl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], IOExcepti
   on
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Comma
   nds.InvokeWebRequestCommand

ERROR: Service 'dotnetsdk' failed to build : The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v$env:NUGET_VERSION/nuget.exe" -UseBasicParsing -OutFile "$env:ProgramFiles\NuGet\nuget.exe"' returned a non-zero code: 1</pre>

**Comment by nickwesselman** [comment]
@krtarwood Are you on a workstation that may have domain or network restrictions? Can you run the following command from an admin PowerShell prompt on the container host?

```
Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v5.8.0/nuget.exe" -UseBasicParsing -OutFile nuget.exe
```

**Comment by krtarwood** [comment]
@nickwesselman very possible - the machines are on a company network (either via VPN or on-prem). I was able to run that command on the same container host and nuget.exe downloaded to the local directory. I was running powershell as an administrator for this command and for the docker-compose.

**Comment by nickwesselman** [comment]
@krtarwood Two things to try:

* Add the following to `dotnetsdk` Dockerfile, before the `Invoke-WebRequest` call
```
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
```

* Try the NuGet download on its own
```powershell
docker run -it --env NUGET_VERSION=5.8.0 mcr.microsoft.com/dotnet/framework/sdk:4.8 powershell.exe
# then inside the container shell
Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v$env:NUGET_VERSION/nuget.exe" -UseBasicParsing -OutFile "$env:ProgramFiles\NuGet\nuget.exe"
```

**Comment by krtarwood** [comment]
@nickwesselman the first change to the dotnetsdk Dockerfile didn't seem to correct the error, and the second sequence resulted in the same error as well when I ran the Invoke-WebRequest.

**Comment by nickwesselman** [comment]
@krtarwood Can you confirm your Docker and Windows 10 version? But tbh this sounds like an issue specific to your company network.

**Comment by krtarwood** [comment]
@nickwesselman Running Windows 10 Pro (10.0.18363) with Docker Windows Desktop 3.1.0 (51484). I have a feeling you're correct, though the command doesn't produce an error locally. I initially suspected it had more to do with filesystem permissions in the container than networking. I'll see if there are any firewall rules or antivirus filters mucking things up. Thank you for the help!

**Comment by krtarwood** [comment]
@nickwesselman I also tried adding -verbose to the command in the Dockerfile. It makes it look like it's receiving the response stream but can't write to disk.

<pre>Step 6/10 : RUN Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v$env:NUGET_VERSION/nuget.exe" -UseBasicParsing -OutFile "$env:ProgramFiles\NuGet\nuget.exe" -verbose
 ---> Running in 1e0c8de40e63
VERBOSE: GET https://dist.nuget.org/win-x86-commandline/v5.8.0/nuget.exe with
0-byte payload
VERBOSE: received 6718360-byte response of content type
application/x-msdownload
Invoke-WebRequest : A required privilege is not held by the client.
At line:1 char:76
+ ... yContinue'; Invoke-WebRequest https://dist.nuget.org/win-x86-commandl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], IOExcepti
   on
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Comma
   nds.InvokeWebRequestCommand
</pre>

**Comment by nickwesselman** [comment]
Stale, please reopen if you are still seeing this on a recent release, still seems like an environment-specific issue.
