### ISSUE TITLE
Docker throws build error when project reference added to rendering project

### ISSUE THREAD

**Issue by dspoincelot** [Sitecore/Helix.Examples#109]
When a project reference is added from a platform project (4.8) to a rendering project (Core 3.1) Docker fails to build the rendering container. There is no issue building it locally with Visual Studio. I encountered this when adding a language selector. The multisite project reference was added to the navigation rendering project to add it to the header. However, I can reproduce it with a blank 4.8 project, so it's not related to the specific project code.

I get this error:

Step 16/20 : RUN dotnet publish -c $env:BUILD_CONFIGURATION -o C:\out\rendering --no-restore
 ---> Running in d13c56a35bfd
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

C:\build\src\Foundation\Multisite\platform\BasicCompany.Foundation.Multisite.Platform.csproj(86,1): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\5.0.103\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\5.0.103\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" is correct, and that the file exists on disk.
ERROR: Service 'solution' failed to build : The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; dotnet publish -c $env:BUILD_CONFIGURATION -o C:\out\rendering --no-restore' returned a non-zero code: 1

**Comment by nickwesselman** [comment]
@dspoincelot Not really an issue we would solve in Helix Examples as it's implementation specific. I'm curious though as to why you would reference a platform project on rendering? `dotnet publish` will not be able to handle Web App projects, as the error indicates. If you have shared code, you likely need to put it in a `netstandard20` shared class library.

**Comment by dspoincelot** [comment]
Ah, understood and thanks for the quick response.  As for the reference, the multisite project lives under BasicCompany.Foundation.Multisite.Platform. I add the view component to the header in the navigation rendering project. Also in the rendering project is a model that refences the multisite platform. Maybe my thought process is the issue? Below is the model in the navigation rendering that lets me build the view component (also on the navigation platform).

[SitecoreComponentField]
public SupportedLanguage[] SupportedLanguages { get; set; }

**Comment by nickwesselman** [comment]
@dspoincelot These sound like they should all be rendering host projects / netcore3.1, not sure what you are trying to put in "platform" for multisite (should only be code that deploys to the CM/CD). If you are trying to share a model between the two, that is currently challenging due to the dependencies brought in by the attributes.

In any case, Sitecore Stackexchange or Community Slack would be a better venue for this question.
