### ISSUE TITLE
'Invoke-WebRequest' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by stephenvselvaraj** [Sitecore/Helix.Examples#124]
Issue # 1
Step 6/10 : RUN Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v$env:NUGET_VERSION/nuget.exe" -UseBasicParsing -OutFile "$env:ProgramFiles\NuGet\nuget.exe"
 ---> Running in 295537060f5c
'Invoke-WebRequest' is not recognized as an internal or external command,
operable program or batch file.
The command 'cmd /S /C Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v$env:NUGET_VERSION/nuget.exe" -UseBasicParsing -OutFile "$env:ProgramFiles\NuGet\nuget.exe"' returned a non-zero code: 1
ERROR: Service 'dotnetsdk' failed to build : Build failed

![image](https://user-images.githubusercontent.com/85010010/120651235-7438da00-c476-11eb-9670-43ac639cce71.png)

![image](https://user-images.githubusercontent.com/85010010/120651661-ed383180-c476-11eb-8c50-f212a4e8fb96.png)

![image](https://user-images.githubusercontent.com/85010010/120651304-8ca8f480-c476-11eb-8f8a-73b0b1e1974d.png)

Issue # 2 : SitecoreAdminPassword, _init.ps1 line 13:  How to handle this?. Please advice
    # We do not need to use [SecureString] here since the value will be stored unencrypted in .env,
    # and used only for transient local example environment.
    [string]
    $SitecoreAdminPassword = "b"

![image](https://user-images.githubusercontent.com/85010010/120650766-068cae00-c476-11eb-9023-73e3a0e6dd7b.png)

**Comment by stephenvselvaraj** [comment]
.NET Framework version = 4.8.4084.0
Powershell version = 7.1.3
Windows 10 = Pro
System Type =64-bit x64-based processor
Net.SecurityProtocolType = 
SystemDefault
Ssl3
Tls
Tls11
Tls12
Tls13

**Comment by K-Cyganiak** [comment]
@stephenvselvaraj  Try to add "SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]" to relevant DockerFile above RUN command or change RUN to CMD.

**Comment by nickwesselman** [comment]
The default shell for the base image here changed to `cmd` at some point. Latest release now includes the needed SHELL command.
