### ISSUE TITLE
.NET Core Sample rendering host doesn't startup

### ISSUE THREAD

**Issue by kythorn** [Sitecore/Helix.Examples#125]
The rendering container doesn't startup, and fails with the following error:

```
Recreating basic-company-aspnetcore_rendering_1 ... error

ERROR: for basic-company-aspnetcore_rendering_1  Cannot start service rendering: container 3a2c43efceb4489e0e40e449a27673e29d2f0a27ffa3a2dfdd9f392f7058b1fc encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)

ERROR: for rendering  Cannot start service rendering: container 3a2c43efceb4489e0e40e449a27673e29d2f0a27ffa3a2dfdd9f392f7058b1fc encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106)
ERROR: Encountered errors while bringing up the project.
```

This seems related to mounting .\ as c:\solution. I do not know why.

Mounted .\ as c:\solution2 to ensure docker has no issues mounting .\ in general. That succeeded, but the watch task fails.

As a potential workaround, I tried to instead mount .\src as c:\solution\src but then the nuget.config isn't found and package restores fail.

On windows, you cannot bind a single file, so I'm not sure where to go from here.

Unclear when/why this stopped working. Is this working for everyone else?

In case it's relevant:
```
docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:56:41 2021
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Comment by kythorn** [comment]
I believe this is related to this older issue pertaining to mapping a volume that already exists in a windows container: https://github.com/docker/for-win/issues/192

The mount in question seems to be key to being able to build containers to publish but also have rapid feedback while using the .net core rendering image. The MVP sample site uses the same approach and has the same issue. The other hosts don't run into this because of the robocopy from c:\src based approach.

Because there aren't widespread reports across these two projects, I'm going to assume somehow the manifestation for me is tied to some local variable. I'm going to completely remove docker, do a fresh install and report back.

**Comment by kythorn** [comment]
Findings to future people who may stumble on this issue:

On Win10 20H2 using a SOLUTION_BUILD_IMAGE of mcr.microsoft.com/dotnet/framework/sdk:4.8 works as expected
On Win10 21H1 using a SOLUTION_BUILD_IMAGE of mcr.microsoft.com/dotnet/framework/sdk:4.8 fails as outlined above
On Win10 21H2 using a SOLUTION_BUILD_IMAGE of mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-20H2 works as expected

I don't know the difference between sdk:4.8 and sdk:4.8-windowsservercore-20H2. Browsing dockerhub I thought both tags resolved to the some version, but they're definitely behaving differently in practice.

Given that it fails to even start the container and fails with no meaningful error message, I am not sure where to go from here. Is this a docker for windows issue? Is it a Microsoft base image issue?

**Comment by K-Cyganiak** [comment]
I confirm this issue. In my case I am on windows 21H1 and after using sdk:4.8-windowsservercore-20H2 workaround  i also had to edit dotnetsdk Dockerfile and add "SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]" before COPY and changed RUN in Invoke-Request to CMD to get nuget (Was getting cannot establish secure ssl/tls channel with RUN command).

**Comment by nickwesselman** [comment]
@K-Cyganiak This sounds like a different issue.

@kythorn The repository now defaults to SDK for LTSC2019. I didn't see your specific issue, but using the `4.8` tag on some SAC builds actually resulted in the LTSC2016 being pulled. Usually this manifested in [TLS 1.2 errors with nuget.exe](https://sitecore.stackexchange.com/questions/29557/container-based-solution-build-errors-with-could-not-create-ssl-tls-secure-chan/29558#29558). If you haven't yet, you should potentially report this issue to the [Moby project](https://github.com/moby/moby), which manages Windows containers.
