### ISSUE TITLE
DataSource templates in Helix.Examples don't seem to follow Helix documentation

### ISSUE THREAD

**Issue by mstodd** [Sitecore/Helix.Examples#128]
From 2.5.3 Template Types:

> Datasource template
> Items from this template are referenced by renderings as a datasource.

From 2.5.3.3. Datasource template:

> Datasource templates live only in the Project layer and typically do not have fields themselves.

Templates such as "Promo Card" and "Accordion Item" are Datasource templates as they're used by renderings as datasources and appear to be in the "feature" layer and do have their own fields.

**Comment by nickwesselman** [comment]
Hey @mstodd -- There is a long overdue pending update to Helix Docs related to this. Consensus of the community seems to be that interface templates aren't always needed for Datasources, especially considering that the platform doesn't natively enable this.

https://github.com/Sitecore/Helix.Docs/issues/30
