### ISSUE TITLE
Support for Containerized/Remote Solr

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/Helix.Examples#62]
Not everyone installs Solr locally, should the examples support that? Requires modifications to the builtin SIF configs.

**Comment by sshushliapin** [comment]
Nevertheless, would it make sense to enable docker support as alternative to the existing scripts? That's just a matter of very few files (`docker.compose.yml`, `Dockerfile` and few `.gitempty`). See my [feature/docker](https://github.com/sshushliapin/Helix.Examples/commits/feature/docker) branch.

P.S.: I tried to run `install.ps1` but gave up after few 'wrong' answers and continuously restarting wizard. When one have docker images in place, that's much easier.

**Comment by nickwesselman** [comment]
Closing due to switch to use of containers... for everything. :)
