### ISSUE TITLE
Use SDK-style project format

### ISSUE THREAD

**Issue by sshushliapin** [Sitecore/Helix.Examples#68]
Is there any reason to use [old .NET Framework project format](https://github.com/Sitecore/Helix.Examples/blob/master/examples/helix-basic-unicorn/src/Feature/Products/website/BasicCompany.Feature.Products.csproj)? [SDK-style projects](https://docs.microsoft.com/en-us/nuget/resources/check-project-format) are much easier to maintain. Especially in Helix solutions that usually contain numerous projects.

**Comment by nickwesselman** [comment]
Hi @sshushliapin -- Considered it, I know the benefits and it's gaining momentum in the community, but given that SDK-style projects are not officially supported with ASP.NET (dotnet/project-system#2670), it's not something Sitecore can officially endorse (and support) at this time.
