### ISSUE TITLE
Update to Sitecore 9.3

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/Helix.Examples#76]

**Comment by sshushliapin** [comment]
Does [Sitecore.Platform.Assemblies 9.2.0 rev. 002893.csv](https://github.com/Sitecore/Helix.Examples/blob/master/examples/helix-basic-unicorn/src/Environment/Website/Sitecore.Platform.Assemblies%209.2.0%20rev.%20002893.csv) file needs to be updated/renamed to reflect 9.3 versions? If yes, I'll come up with a new issue.

**Comment by nickwesselman** [comment]
@sshushliapin There's actually a better way of doing this now, that I will be PRing soon. :) Good catch though.

**Comment by nickwesselman** [comment]
@sshushliapin FYI, see https://github.com/Sitecore/Helix.Examples/pull/83/files
