### ISSUE TITLE
Running install.ps1 throws error

### ISSUE THREAD

**Issue by Antonytm** [Sitecore/Helix.Examples#78]
Steps to reproduce 
1. Run .\install.ps1
2. Enter $SqlServer, $SqlAdminUser ... $SolrService variables
Actual result: error is thrown:
> Exception calling "ReadKey" with "0" argument(s): "Cannot read keys when either application does not have a console or when console input has 
> been redirected from a 
> file. Try Console.Read."
> At C:\Sources\Helix.Examples\install-modules\helix.examples.menu.psm1:38 char:5
> $null = [Console]::ReadKey()
> CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
> FullyQualifiedErrorId : InvalidOperationException

![image](https://user-images.githubusercontent.com/647813/72076480-40e43100-32fe-11ea-8cd3-a5b37ea0112c.png)

Expected result: no exception

**Comment by nickwesselman** [comment]
Hi @Antonytm -- Are you running within a regular PowerShell prompt, in a VS Code terminal, or...?

**Comment by Antonytm** [comment]
Hi @nickwesselman 
I used PowerShell ISE. and after googling I see that it is an issue only there.
It works fine within a regular PowerShell prompt.

**Comment by nickwesselman** [comment]
@Antonytm yeah it requires an interactive console. I need to make the docs more explicit on this. Thanks for reporting.
