### ISSUE TITLE
 Validation/prerequisites error 

### ISSUE THREAD

**Issue by aiorgu** [Sitecore/Helix.Examples#79]
Hey guys. I am having issues running the installer, despite that I;ve followed all the steps and made sure all the prerequisites are in place. 

Does this trigger anything to you?

I do have all these in place and the configuration should be good
```
SQL Server 2016 SP2
Apache Solr 7.5.0 with SSL enabled
.NET Framework 4.7.2
```

![image](https://user-images.githubusercontent.com/1710440/74935182-83665680-53f0-11ea-9fa7-6229a2db5dde.png)

Also the connections appear to be fine:
![image](https://user-images.githubusercontent.com/1710440/74935775-8b72c600-53f1-11ea-8637-cb594adbce26.png)

Thank you in advance

**Comment by nickwesselman** [comment]
Hi @aiorgu! What happens if you just run `.\prepare.ps1` from the same directory?

**Comment by aiorgu** [comment]
Hi @nickwesselman! Thank you, that fixed my issues.
