### ISSUE TITLE
Cant install helix example with unicorn

### ISSUE THREAD

**Issue by mrleopoldus** [Sitecore/Helix.Examples#80]
OS: Windows 10, When installing helix unicorn via install.ps1 I get the following error:

> "Install-SitecoreConfiguration : Could not load file or assembly                                                         'file:///C:\Projects\Helix.Examples\install-modules\unicorn\MicroCHAP.dll' or one of its dependencies. Operation is     not supported. (Exception from HRESULT: 0x80131515)                                                                     At C:\Projects\Helix.Examples\examples\helix-basic-unicorn\build\install.ps1:50 char:9                                  +         Install-SitecoreConfiguration @singleDeveloperParams *>&1 | T ...                                             +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                         + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException                                          + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-SitecoreConfiguration"

![image](https://user-images.githubusercontent.com/28565577/75348468-cca82180-589a-11ea-815b-4efa95193fd0.png)

While the dll file is in this directory (cloned directly from master)
![image](https://user-images.githubusercontent.com/28565577/75348541-f9f4cf80-589a-11ea-9b50-e1e440ad261f.png)

How can I circumvent this?

**Comment by nickwesselman** [comment]
@mrleopoldus Thanks for the issue report. Did you download the repository as a zip? Can you confirm whether you can "unblock" it before unzipping, and whether that resolves the issue?

https://singularlabs.com/tips/how-to-unblock-a-zip-file-on-windows-10/

**Comment by michaellwest** [comment]
I bet the helix examples were downloaded as a zip and the file was not "unblocked" before extracting.
