### ISSUE TITLE
Grant IIS App Pool required access to project directory

### ISSUE THREAD

**Issue by dsolovay** [Sitecore/Helix.Examples#89]
While attempting to install, I ran into this error:
![image](https://user-images.githubusercontent.com/689532/81254675-cd2b0a00-8ff9-11ea-9731-a57fc9e22957.png)

`Install-SitecoreConfiguration : Server Error in '/' Application.                                                                                            Access to the path 'C:\Users\dsolovay\projects' is denied.                                                                                                  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the  error and where it originated in the code.                                                                                                                  Exception Details: System.UnauthorizedAccessException: Access to the path 'C:\Users\dsolovay\projects' is denied.                                           ASP.NET is not authorized to access the requested resource. Consider granting access rights to the resource to the ASP.NET request identity. 
`
Recommendation: Modify script to grant access if feasible, or determine required manual remediation before install begins.

**Comment by nickwesselman** [comment]
Closing due to switch to use of containers.
