### ISSUE TITLE
Image scr.sitecore.com/sxp/sitecore-xm1-mssql:10.0.0-ltsc2019 looks broken

### ISSUE THREAD

**Issue by IvanFedorychak** [Sitecore/Helix.Examples#93]
When I try to pull this image I always receive error like:
48a55f8e2ae1: Download complete
failed to register layer: rename C:\ProgramData\Docker\image\windowsfilter\layerdb\tmp\write-set-647907111 C:\ProgramData\Docker\image\windowsfilter\layerdb\sha256\2754b2e2bebcddaa86b90bce763324b9546c25c684c44333d7a81f7b87f687f8: Access is denied.

It happens with f661de4fced9 layer

**Comment by nickwesselman** [comment]
Hi @IvanFedorychak,

This appears to be an issue on your workstation. Can you confirm you are running as admin? Also try disabling any anti-virus you have running, or configuring it to ignore your Docker folder.

**Comment by IvanFedorychak** [comment]
Hi @nickwesselman 

Yes, looks like a false alarm. Sorry about that.
Checked on another box works as expected.

Regards,
Ivan
