### ISSUE TITLE
helix-basic-unicorn: System.Threading.LockRecursionException: 

### ISSUE THREAD

**Issue by arthurbai** [Sitecore/Helix.Examples#96]
version: sitecore 10

[LockRecursionException: If the write lock remains in this mode, the read lock may not be obtained.]
   System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout) +1347
   System.Threading.ReaderWriterLockSlim.TryEnterReadLock(TimeoutTracker timeout) +44
   Sitecore.DependencyInjection.ServiceLocator.get_ServiceProvider() +176
   Sitecore.DependencyInjection.<>c__16`1.<GetRequiredResetableService>b__16_0() +19
   Sitecore.DependencyInjection.LazyResetable`1.get_Value() +150
   Sitecore.Configuration.ConfigReader.ResolveVariables(StringDictionary variables) +1227
   Sitecore.Configuration.ConfigReader.ReplaceGlobalVariables(XmlNode rootNode) +842
   Sitecore.Configuration.ConfigReader.DoGetConfiguration() +522
   Sitecore.Configuration.ConfigReader.GetConfiguration() +236
   Sitecore.DependencyInjection.ServiceLocator.ConfigureServiceProvider() +13
   Sitecore.DependencyInjection.ServiceLocator.get_ServiceProvider() +513
   Sitecore.DependencyInjection.SitecorePerRequestScopeModule..ctor() +13

**Comment by nickwesselman** [comment]
Hi @arthurbai -- Can you please provide more detail on the conditions in which you saw this error? It doesn't look like an issue specific to this sample.

**Comment by cassidydotdk** [comment]
Ancient news, but likely related to this: https://github.com/Sitecore/Helix.Examples/blob/22f1414490bf75e6bea98f4624f64cf2c28566d8/examples/helix-basic-unicorn/src/Foundation/Serialization/website/App_Config/Include/Foundation/Foundation.Serialization.config#L11

And this: https://github.com/SitecoreUnicorn/Unicorn/issues/352

**Comment by Ameexramesh** [comment]
Hi, 

Now, the sc variable is <sc.variable name="sourceFolder" value="$(env:ITEM_SYNC_LOCATION)" />  in the file. but i received same error.

kindly help me.

**Comment by nickwesselman** [comment]
Did you set the `ITEM_SYNC_LOCATION` environment variable?

**Comment by Ameexramesh** [comment]
Downloaded the helix 10.0.1 solution from github and setup the local environment with 10.0.1 instance. I created published profile from helix solution to Sitecore instance solution. I click publish.

I didn't sent any environment variable. and where i can set environment variable?

**Comment by nickwesselman** [comment]
Please reopen if still reproducing on most recent release.
